-- Database Setup
CREATE OR REPLACE DATABASE SNOW_SAMPLE_DB comment = 'Sample Data DB';

-- Schema Setup
CREATE OR REPLACE SCHEMA SAMPLE_SCHEMA comment = 'Sample Data Schema';

-- Table Setup
CREATE TABLE CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

CREATE TABLE NATION AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
